# Generated by Django 5.1.2 on 2024-10-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_seller_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('USER', 'User')], max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('N', 'NO'), ('S', 'Suspended'), ('B', 'Blocked'), ('Y', 'YES')], max_length=1),
        ),
    ]
