# Generated by Django 5.1.2 on 2024-10-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_role_alter_seller_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('N', 'NO'), ('Y', 'YES'), ('S', 'Suspended'), ('B', 'Blocked')], max_length=1),
        ),
    ]
