# Generated by Django 5.1.2 on 2024-10-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_seller_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('N', 'NO'), ('S', 'Suspended'), ('B', 'Blocked'), ('Y', 'YES')], max_length=1),
        ),
    ]
