# Generated by Django 5.1.2 on 2024-11-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_seller_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('B', 'Blocked'), ('N', 'NO'), ('Y', 'YES'), ('S', 'Suspended')], max_length=1),
        ),
    ]
