# Generated by Django 5.1.2 on 2024-10-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('S', 'Suspended'), ('Y', 'YES'), ('N', 'NO'), ('B', 'Blocked')], max_length=1),
        ),
    ]
