# Generated by Django 5.1.2 on 2024-10-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_seller_seller_status'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '__first__'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('N', 'NO'), ('S', 'Suspended'), ('B', 'Blocked'), ('Y', 'YES')], max_length=1),
        ),
    ]
