# Generated by Django 5.1.2 on 2024-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='product_code',
            field=models.CharField(default=' ', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
