# Generated by Django 5.1.2 on 2024-10-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_seller_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='item_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
