# Generated by Django 5.1.2 on 2024-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_seller_product_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='item',
            new_name='related_product',
        ),
        migrations.RenameField(
            model_name='seller_product',
            old_name='product_code',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image_id',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
