# Generated by Django 5.1.2 on 2024-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_models',
            name='seller',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
