# Generated by Django 5.1.2 on 2024-10-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_seller_models_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_models',
            name='seller',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO'), ('B', 'Block'), ('S', 'Suspended')], max_length=1),
        ),
    ]
