# Generated by Django 5.1.2 on 2024-10-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('B', 'Blocked'), ('N', 'NO'), ('S', 'Suspended'), ('Y', 'YES')], max_length=1),
        ),
    ]
